### ISSUE TITLE
Not able to transliterate digraphs.

### ISSUE THREAD

**Issue by tomicakorac** [malexer/SublimeTranslit#2]
Hi @malexer 

I can't seem to make this package work with digraphs. I've created two dictionaries, to convert from Croatian (Latin) to Serbian (Cyrillic) and vice versa, from Serbian to Croatian. In each of them there are three specific points involving digraphs:

```
# Croatian to Serbian
(LJ|Lj) -> Љ / lj -> љ
(NJ|Nj) -> Њ / nj -> њ
(DŽ|Dž) -> Џ / dž -> џ

# Serbian to Croatian
Љ -> Lj / љ -> lj
Њ -> Nj / њ -> nj
Џ -> Dž / џ -> dž
```

Now, converting from Serbian to Croatian works as expected (for instance, `љ` is always correctly substituted with `lj`). However, the opposite direction never works (`lj` will always get substituted with `лј`, which is wrong).

For reference, here are all my dictionaries' files:
- Croatian to Serbian:
  - [croat_serb.sublime_commands](http://laravel.io/bin/d96av)
  - [croat_serb.dict](http://laravel.io/bin/Kk83q)
- Serbian to Croatian:
  - [serb_croat.sublime_commands](http://laravel.io/bin/xKGLQ)
  - [serb_croat.dict](http://laravel.io/bin/eDzjj)

Can you please help me find a solution?

**Comment by malexer** [comment]
Hi @tomicakorac 

Originally I was targeting the single task: transliterate the Cyrillic text into latin.

The opposite direction was not implemented mainly because sometimes it is hard to do it by a simple substitution.

Considering your case, for "Croatian to Serbian" there are:

```
"j" -> "j"
"l" -> "л"
"lj" -> "љ"
```

If we see "lj" chars in a word which option should we choose: "љ" or "лj" ?
We need some more extended rules here, simple mapping is not enough unfortunately.

May be I am missing something?

There might be some additional rules I am not aware about as I don't speak Croatian and Serbian. i.e. some priority rules:
1. "lj" -> "љ" is always used first
2. "j" -> "j" and "l" -> "л" are applied then.

Do you have any such additional rules described somewhere?

**Comment by tomicakorac** [comment]
Hi again and thank you very much for such a quick reply!

You're not missing anything actually, you were spot on!

In Croatian language, the combinations: `lj`, `nj` and `dž` will **always** mark one sound each. That's why they're digraphs, and not just any ordinary combination of two letters. Even more, in Croatian alphabet they exist as stand-alone letters, even though they're written using two letters: `...,i,j,k,l,lj,m,n,nj,o,....`.

On the other hand, Serbian and Croatian are **not** two separate languages. They are essentially one and the same language with no differences whatsoever, except one: Croatian uses Latin script, whereas Serbian uses Cyrillic. Accordingly, for each letter in Croatian (Latin), there is a corresponding letter in Serbian (Cyrillic).

All this means that, when transliterating from Croatian to Serbian, each and every combination of `lj`, `nj` and `dž` will **always** be substituted with `љ`, `њ` and `џ`, respectively. As a result of this, you will **never** find in Serbian any of such combinations: `лј`, `нј`, `дж`. They do not exist.

Logically enough, the same is true in the opposite direction: `љ`, `њ` and `џ` will **always** be substituted with `lj`, `nj` and `dž`.

For upper case Croatian, forms `Lj`, `Nj`, `Dž` are preferred.

Finally, please note that Serbian (Cyrillic) language uses this letter: `Јј`, which is exactly same as Latin `Jj`, but it uses a separate Unicode point.

Please let me know if I can be of any more help.

**Comment by malexer** [comment]
I have added two-side transliteration.

Note: there are two separate mappings because:
1. Croatian -> Serbian: "đ" and "dj" both transliterated to "ђ"
2. Serbian -> Croatian: it seems that "ђ" is always transliterated as "đ"

Is it correct?

**Comment by tomicakorac** [comment]
Oh, I'm very sorry for missing that one. Well you're almost right. When transliterating from Croatian to Serbian:
- `đ` should always be transliterated as `ђ`;
- `dj` should always be transliterated as `дј`;

Transliterating from Serbian to Croatian, the same rules apply, but obviously in the opposite directions: `ђ` > `đ`, `дј` > `dj`.

The confusion that both `đ` and `dj` can and should be transliterated as `ђ` is incorrect. This confusion originates from Slovene language, which does not have the letter `đ`, but instead writes `dj` for the same voice. However this is irrelevant for our problem, because Slovene language is quite different to Serbocroatian, and could not be meaningfully transliterated in the first place.

Thank you very much for your effort Alex!

**Comment by malexer** [comment]
Thanks for your explanation!

I have updated the mapping.

There is a unittest with pangram to verify that transliteration is working but you can also verify from your side as a native speaker as well.

Thanks!
