### ISSUE TITLE
Not Working, ST3 3126

### ISSUE THREAD

**Issue by dc-avasilev** [malexer/SublimeTranslit#3]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
TypeError: run() missing 1 required positional argument: 'invert_mapping'

**Comment by malexer** [comment]
Hi @dc-avasilev ,

Can you add steps to reproduce?

Thanks!

**Comment by malexer** [comment]
I believe in your case old .sublime-commands file was used for some reason. 
Some files have changed their names and my guess was that on some configuration SublimeTranslit can have both old and the new ones after update.

I've tried to reproduce it on Linux and MacOS - updating old version of SublimeTranslit to the latest one but no luck, in my case it was fully working.

How did you install the SublimeTranslit? Have you used Package Control or installed it manually?

**Comment by malexer** [comment]
Anyway I have added the fix to read that .sublime-commands files from previous version
