### ISSUE TITLE
Can this amazing tool be packaged for Atom?

### ISSUE THREAD

**Issue by tomicakorac** [malexer/SublimeTranslit#9]
A simple question, I hope: I have the need to use Atom text editor, and I would be very happy to have this tool available in Atom as well. How simple (or complex) would it be to create an Atom package with the same functionality?

**Comment by malexer** [comment]
Hi @tomicakorac , I am not a user of Atom editor, so consider these as my assumptions.

It seems that Atom supports writing plugins in JavaScript, so it will be hard to do just some copy-paste.
But the whole logic of the plugin is not complex, so it should be possible to rewrite it into JS and publish as Atom package.
Unfortunately, this is not on my backlog currently.

Feel free to fork the project and reuse any code and mappings if you are willing to port it.
